#!/bin/bash

if [ -z "$1" ]; then
	echo "No file specified.  Please specify a csv file containing Pythagorean Triplets."
	exit 1
fi

cat $1|while read x; do y=$(echo $x|cut -d , -f 1);z=$(echo $x|cut -d , -f 2);a=$(dc -e "$y $z * 2 / p"); echo $a;done

exit $?
