#!/usr/bin/env bash

if [[ $# < 1 ]]; then
        echo "DB name must be provided on the command line."

        exit 1
fi

db_name=$1
shift

mysql -Ns $@ -e 'show tables' ${db_name} | while read table; do echo mysql $@ -e "SET FOREIGN_KEY_CHECKS=0; truncate table \`${table}\`" ${db_name}; done

