#!/usr/bin/env bash

if [ -f "$1" ]; then
  case "$1" in
    *.tar.bz2)   tar xjf "$1";;
    *.tar.gz)    tar xzf "$1"    ;;
    *.bz2)       bunzip2 "$1"      ;;
    *.rar)       rar x "$1"    ;;
    *.gz)        gunzip "$1"    ;;
    *.tar)       tar xf "$1"       ;;
    *.tbz2)      tar xjf "$1"     ;;
    *.tgz)       tar xzf "$1"      ;;
    *.zip)       unzip "$1"    ;;
    *.Z)         uncompress "$1" ;;
    *.7z)        7z x "$1"   ;;
    *.lz)        plzip -d "$1"   ;;
    *.lzo)       lzop -x "$1"   ;;
    *.lzop)      lzop -x "$1"   ;;
    *.lrz)       lrzip -d "$1"   ;;
    *.tlz)       tar --use-compress-program=plzip -xf "$1"   ;;
    *.tar.lz)    tar --use-compress-program=plzip -xf "$1"   ;;
    *.tlzo)      tar --use-compress-program=lzop -xf "$1"   ;;
    *.tar.lzo)   tar --use-compress-program=lzop -xf "$1"   ;;
    *.tar.lzop)  tar --use-compress-program=lzop -xf "$1"   ;;
    *.tlrz)      lrzuntar "$1"   ;;
    *.tar.lrz)   lrzuntar "$1"   ;;
    *)           echo "'$1' cannot be extracted via extract()" ;;
  esac
else
  echo "'$1' is not a valid file"
fi

exit $?
