#!/usr/bin/env bash

folders='*'
action='pwd'
inserial=false

USAGE="$(basename $0) <options> \n
\n
\t      Perform the given action in the specified folders. \n
\n
\t      Options \n
\n
\t\t            [-h|--help]\t\t\t                     This message gets printed only. \n
\t\t            [-f|--folders] <the folders>\t  Each folder to perform the specified action in.  Default: \"${folders}\" \n
\t\t            [-a|--action] <the action>\t    The action to perform.  Default: \"${action}\" \n
\t\t            [-s|--serial] <serial>\t    Execute action serially, not parallelly.  Default: \"${inserial}\" \n
"

args=`getopt -o "hf:a:s" -l "help,folders,action,serial" -- "$@"`
eval set -- "$args"
while true; do
  case "$1" in
                -h | --help)    echo -e ${USAGE}; exit;;
                -f | --folders)  shift; folders="$1"; shift;;
                -a | --action)  shift; action="$1"; shift;;
                -s | --serial)  shift;;
                --) shift; break;;
                *) echo "Internal error!"; exit 1;;
  esac
done

if [[ -f "foreach_order.txt" ]]; then
	if [[ ${inserial} ]]; then
		cat foreach_order.txt | while read x; do bash -c "cd $x; ${action}"; done
	else
		lsp -a "$(cat foreach_order.txt)" "cd {}; ${action}"
	fi
else
	if [[ ${inserial} ]]; then
		echo ${folders} | while read x; do bash -c "cd $x; ${action}"; done
	else
		lsp -a "${folders}" "cd {}; ${action}"
	fi
fi

