#!/bin/bash

USAGE="git_status_files -c <the \"git status -s\" output characters>"

characters='[ |A|M|R|D|C][ |A|M|R|D|C] '

args=`getopt -o "c:h" -l "characters:,help" -- "$@"`
eval set -- "$args"
while true; do
  case "$1" in
		-h | --help)		echo "${USAGE}"; exit 0;;
		-c | --characters)	shift; characters="$1";	shift;;
		--)	shift;			break;;
		*)	echo "${USAGE}";	exit 1;;
  esac
done

if [ -z "${characters}" ]; then
	echo "${USAGE}"
	exit 1
fi

git status -s | grep "^${characters}" | sed "s/^${characters}//" | awk '{ print $NF }'

