#!/bin/bash

args=`getopt -o "f:m:t:" -l "folder,message" -- "$@"`
eval set -- "$args"
while true; do
  case "$1" in
		-m) shift; message=".$1"; shift;;
		-f) shift; folder="$1"; shift;;
		-t) shift; target="$1"; shift;;
		--) shift; break;;
		*) echo "Internal error!"; exit 1;;
  esac
done

if [ -n "${folder}" ]; then
	the_name="$(basename "${folder}")"
	the_target="${folder}"
else
	the_name="$(basename "$(pwd)")"
	the_target="."
fi

target_folder=~/back
if [ -n "${target}" ]; then
	target_folder="${target_folder}/${target}"
fi

if [ -n "${message}" ]; then
	message=$(echo "${message}" | tr ' ' '_')
fi

git_revision=$(git_short_revision "${the_target}")

if [ -n "${git_revision}" ]; then
	the_filename="${target_folder}/${the_name}.rev${git_revision}.$(now).untracked${message}.tlzo"
	the_unknown_files=$(git_status_files -c ??)
else
	the_filename="${target_folder}/${the_name}.$(now).untracked${message}.tlzo"
	the_unknown_files="*"
fi

if [ -z "${the_unknown_files}" ]; then
	echo "No file found for backup."
	exit 0
fi

tar --use-compress-program=lzop -cf ${the_filename} ${the_unknown_files}

exit $?
