#!/usr/bin/env bash

grep_excludes_file="${HOME}/stuff/grep_excludes_for_lspf.txt"

if [[ -f "${grep_excludes_file}" ]]; then
	cmd="lsp \"find $@\" | grep -vf \"${grep_excludes_file}\""
else
	cmd="lsp \"find $@\""
fi

cmd="${cmd} | sort -ud"

echo "	Executing \"${cmd}\""
bash -c "${cmd}"

exit $?
