#!/usr/bin/env bash

USAGE="$(basename $0) <options> \n
\n
\t      Run \"find\" through \"lsp\". \n
\n
\t      Options \n
\n
\t\t            [-h|--help]\t	This message gets printed only. \n
\t\t            [-q|--quiet]\t	Be quiet. \n
"

be_quiet=false
grep_excludes_file="${HOME}/stuff/grep_excludes_for_lspf.txt"

args=`getopt -o "hq" -l "help,quiet" -- "$@"`
eval set -- "$args"
while true; do
  case "$1" in
                -h | --help)	echo -e ${USAGE}; exit;;
                -q | --quiet)	be_quiet=true; shift;;
                --) shift; break;;
                *) echo "Internal error!"; exit 1;;
  esac
done

if [[ -f "${grep_excludes_file}" ]]; then
	cmd="lsp \"find $@\" | grep -vf \"${grep_excludes_file}\""
else
	cmd="lsp \"find $@\""
fi

cmd="${cmd} | sort -ud"

[[ ${be_quiet} == false ]] && echo "	Executing \"${cmd}\""

bash -c "${cmd}"

exit $?
