#!/usr/bin/env bash

grep_excludes_file="${HOME}/stuff/grep_excludes.txt"

if [[ -f "${grep_excludes_file}" ]]; then
	lsp "grep -r --exclude-from=${grep_excludes_file} $@" | sort -ud
else 
	lsp "grep -r $@" | sort -ud
fi

exit $?
