#!/usr/bin/env bash

USAGE="$(basename $0) <options> \n
\n
\t	Print all prime numbers less than or equal to the specified number. \n
\n
\t	Options \n
\n
\t\t		[-h|--help]\t\t\t				This message gets printed only. \n
\t\t		[-n|--number] <the number>\t	The number to print all prime numbers less than or equal to. \n
"

args=`getopt -o "hn:" -l "help,number" -- "$@"`
eval set -- "$args"
while true; do
  case "$1" in
		-h | --help)	echo -e ${USAGE};	exit;;
		-n | --number)	shift; number="$1";	shift;;
		--) shift; break;;
		*) echo "Internal error!"; exit 1;;
  esac
done

prime_1=0
echo "1"
echo "2"
for ((i=3; i<=${number};)); do
	for ((j=i-1; j>=2;)); do
		if [ $(expr $i % $j) -ne 0 ]; then
			prime_1=1
		else
			prime_1=0
			break
		fi

		j=$(expr $j - 1)
	done

	if [ $prime_1 -eq 1 ]; then
		echo $i
	fi

	i=$(expr $i + 1)
done
