#!/usr/bin/env bash

#
# A smarter command doing similar to this one may be the "mmv" command.
#

if [[ $# != 2 ]]; then
	echo 'Two arguments expected'
	exit 1
fi

mv -v "$1" "$(dirname $1)/$(basename $2)"

exit $?
