#!/bin/bash

echo -n '<'
/Users/chad/bin/now -n
echo -n '>'

echo -n '/Users/chad/bin/rsync_cp /opt/workspace /Volumes/ots/.'
/Users/chad/bin/rsync_cp /opt/workspace /Volumes/ots/.
exit_code=$?

echo -n '</'
/Users/chad/bin/now -n
echo '>'

exit $exit_code
