#!/bin/bash

echo -n '<'
/Users/chad/bin/now -n
echo -n '>'

echo -n '/Users/chad/bin/rsync_cp /opt/dev /Volumes/RP/.'
/Users/chad/bin/rsync_cp /opt/dev /Volumes/RP/.
exit_code=$?

echo -n '</'
/Users/chad/bin/now -n
echo '>'

exit $exit_code
