#!/bin/bash

for x in $@; do
	if [ -z "$sed_cmd_iwb02" ]; then
		sed_cmd_iwb02="$x"
	else
		sed_args_iwb02="$sed_args_iwb02 $x"
	fi
done

sed $sed_args_iwb02 -n '
1h
1!H
$ {
        g
        '"$sed_cmd_iwb02"'
        p
}
'
exit $?
